service: my-serverless-app

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1 # Optional: AWS-Region
  environment:
      BI_DB_HOST: ${env:BI_DB_HOST}
      BI_DB_USER: ${env:BI_DB_USER}
      BI_DB_PASSWORD: ${env:BI_DB_PASSWORD}
      BI_DB_NAME: ${env:BI_DB_NAME}
      BI_DB_PORT: ${env:BI_DB_PORT}
      NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000

functions:
  # WICHTIGER HINWEIS: Alle BI-bezogenen Funktionen SOLLTEN `queryBi` aus dem `db`-Modul verwenden,
  # um sicherzustellen, dass sie mit der BI-Datenbank interagieren.

  # Lambda-Funktion zum Abrufen aller Verkaufsdaten.
  getSales:
    handler: src/sales/getSales.getSales # Pfad zum Handler-Code der Funktion.
    events: # Ereignisse, die diese Lambda-Funktion auslösen.
      - httpApi: # HTTP API Gateway Event.
          path: /sales # Der API-Pfad für diesen Endpunkt.
          method: get # Die HTTP-Methode.

  # Lambda-Funktion zum Abrufen einer Verkaufszusammenfassung.
  getSalesSummary:
    handler: src/sales/getSalesSummary.getSalesSummary
    events:
      - httpApi:
          path: /sales/summary
          method: get

  # Lambda-Funktion zum Abrufen von Verkaufsdaten als Zeitreihe.
  getSalesTimeseries:
    handler: src/sales/getSalesTimeseries.getSalesTimeseries
    events:
      - httpApi:
          path: /sales/timeseries
          method: get

  # Lambda-Funktion zum Speichern eines neuen Verkaufsdatensatzes.
  postSale:
    handler: src/sales/postSales.postSale
    events:
      - httpApi:
          path: /sales
          method: post

  # Lambda-Funktion zum Abrufen aller Produkte.
  getProducts:
    handler: src/products/getProducts.getProducts
    events:
      - httpApi:
          path: /products
          method: get

  # Lambda-Funktion zum Abrufen eines spezifischen Produkts anhand seiner ID.
  getProductById:
    handler: src/products/getProductById.getProductById
    events:
      - httpApi:
          path: /product/{id} # Pfad mit einem dynamischen Parameter für die Produkt-ID.
          method: get

  # Lambda-Funktion zum Aktualisieren eines spezifischen Produkts anhand seiner ID.
  updateProduct:
    handler: src/products/updateProduct.updateProduct
    events:
      - httpApi:
          path: /product/{id}
          method: put

  # Lambda-Funktion zum Abrufen der Bestseller-Produkte.
  getBestsellers:
    handler: src/products/getBestsellers.getBestsellers
    events:
      - httpApi:
          path: /products/bestseller
          method: get

  # Lambda-Funktion zum Abrufen einer Zusammenfassung für ein spezifisches Produkt.
  getProductSummary:
    handler: src/products/getProductSummary.getProductSummary
    events:
      - httpApi:
          path: /product/{id}/summary
          method: get

  # Lambda-Funktion zum Abrufen aller Plattformen.
  getPlatforms:
    handler: src/platforms/getPlatforms.getPlatforms
    events:
      - httpApi:
          path: /platforms
          method: get

  # Lambda-Funktion zum Abrufen von Dashboard-Daten für einen spezifischen Benutzer.
  getDashboard:
    handler: src/dashboard/getDashboard.getDashboard
    events:
      - httpApi:
          path: /dashboard/{user} # Pfad mit einem dynamischen Parameter für den Benutzernamen.
          method: get

  # Lambda-Funktion zum Speichern/Aktualisieren von Dashboard-Daten für einen spezifischen Benutzer.
  postDashboard:
    handler: src/dashboard/postDashboard.postDashboard
    events:
      - httpApi:
          path: /dashboard/{user}
          method: post

  # Lambda-Funktion zum Abrufen von Versandverzögerungen und -kosten.
  getShippingDelays:
    handler: src/shipping/getShippingDelays.getShippingDelays
    events:
      - httpApi:
          path: /shipping/delays
          method: get

  # Die Sync-Funktion, die sowohl WaWi- als auch BI-Datenbanken nutzt.
  # Diese Funktion ist nicht direkt über HTTP API Gateway zugänglich,
  # sondern kann manuell (z.B. über die AWS Konsole) oder per Zeitplan ausgelöst werden.
  syncWawiToBi:
    handler: src/syncWawiToBi.syncData


plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    log: true
    httpPort: 3001 # Der lokale Server läuft auf Port 3001
    noPrependStageInUrl: true # Kein Prefix für Umgebungen (z. B. dev)

package:
  individually: true # Optional: Nur genutzte Dateien und Dependencies in das Deployment-Paket aufnehmen